apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconsumer-deployment
spec:
  selector:
    matchLabels:
      app: kafkaconsumer-pod
  template:
    metadata:
      labels:
        app: kafkaconsumer-pod
    spec:
      containers:
        - name: kafkaconsumer-container
          image: ghcr.io/arkapravasinha/kafkaconsumer:v0.1.0
          resources:
            limits:
              memory: 50Mi
              cpu: 100m
