apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaproducer-deployment
spec:
  selector:
    matchLabels:
      app: kafkaproducer-pod
  template:
    metadata:
      labels:
        app: kafkaproducer-pod
    spec:
      containers:
        - name: kafkaproducer-container
          image: ghcr.io/arkapravasinha/kafkaproducer:v0.0.1
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
